version: '3'
services:

  jupyter-spark:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jupyter_spark
    user: root
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - ./jupyter/notebooks:/home/work:rw
      - ./jupyter/partitions:/home/paritions:rw
    environment:
      - SPARK_HOME=/usr/local/spark
      - JUPYTER_ENABLE_LAB="yes"
    #  - JUPYTERHUB_API_TOKEN='75875bb89567570c9136ed9506037121ad1a5983d900da7ac85aa7c8af3f166c'
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=4g
